services:

  postgres:
    image: postgres:17
    container_name: multi-tenant-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./multi-tenant-api
      dockerfile: Dockerfile
    container_name: multi-tenant-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SEED_PASSWORD: ${SEED_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres

volumes:
  postgres_data:
